# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-04 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='EntityCategory',
            fields=[
                ('ecid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ForbiddenWord',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='fpl',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='pid')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('forbiddenNum', models.PositiveSmallIntegerField(verbose_name='fn')),
                ('pTime', models.TimeField(verbose_name='pTime')),
                ('pDate', models.DateField(verbose_name='pDate')),
                ('st', models.FloatField(null=True, verbose_name='st')),
                ('simHash', models.BigIntegerField(null=True, verbose_name='simHash')),
                ('c_read', models.PositiveIntegerField(default=0, verbose_name='c_read')),
                ('c_reply', models.PositiveIntegerField(default=0, verbose_name='c_reply')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('kid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='kwl',
            fields=[
                ('kid', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
                ('num', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False, verbose_name='pid')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('forbiddenNum', models.PositiveSmallIntegerField(verbose_name='fn')),
                ('pTime', models.TimeField(verbose_name='pTime')),
                ('pDate', models.DateField(verbose_name='pDate')),
                ('st', models.FloatField(null=True, verbose_name='st')),
                ('c_read', models.PositiveIntegerField(default=0, verbose_name='c_read')),
                ('c_reply', models.PositiveIntegerField(default=0, verbose_name='c_reply')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpinionMonitor.Category')),
                ('entities', models.ManyToManyField(to='OpinionMonitor.Entity')),
                ('fwords', models.ManyToManyField(to='OpinionMonitor.ForbiddenWord')),
            ],
        ),
        migrations.CreateModel(
            name='PassageKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('ratio', models.FloatField(verbose_name='ratio')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpinionMonitor.Keyword')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OpinionMonitor.Passage')),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='keywords',
            field=models.ManyToManyField(through='OpinionMonitor.PassageKeyword', to='OpinionMonitor.Keyword'),
        ),
        migrations.AddField(
            model_name='entity',
            name='ec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OpinionMonitor.EntityCategory'),
        ),
    ]
